version: "2.1"

services:
  mysql:
    image: mysql:5.6.34
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat_system_api_dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 2s
      timeout: 5s
      retries: 30  

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass root
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

  app:
    build: .
    environment:
      RAILS_ENV: development
      ELASTICSEARCH_URL: http://elasticsearch:9200
      DATABASE_URL: mysql2://root:root@mysql:3306/chat_system_api_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
    links:
      - mysql
      - elasticsearch
      - redis
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/workspace
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  dbdata:
  esdata:
  redisdata: