:schedule:
  update_message_counts:
    cron: "0 * * * *" # Runs every hour
    class: "UpdateMessageCount"
    queue: default
  update_chat_counts:
    cron: "0 * * * *" # Runs every hour
    class: "UpdateChatCount"
    queue: default   